### ISSUE TITLE
Ordenar las zonas: error cuando solo hay una. Añadir drag and drop

### ISSUE THREAD

**Issue by VioletaSaez** [avozme/celia-tour#32]
Cuando accedes a la pestaña de zonas hay una flecha que permite ordenarlas manualmente (si solo se ha añadido una zona da un error porque tendrían que existir más zonas para poder posicionar una sobre otra). Además, el icono es algo confuso y no queda del todo claro para qué sirve. Sería interesante poder ordenar esas zonas arrastrándolas y soltándolas con la técnica de drag and drop.

![image](https://user-images.githubusercontent.com/94532650/144230691-6f17a9af-51c4-4db6-8a3c-231d9019e2d8.png)

**Comment by juanmatorres-dev** [comment]
Resuelto el error (error cuando solo hay una) aquí : https://github.com/avozme/celia-tour/issues/41

**Comment by juanmatorres-dev** [comment]
- [ ] Cargar jQuery UI en la vista de zonas
- [ ] Añadir drag & drop con jQuery 
- [ ] Obtener por JavaScript los ids en orden de las zonas

**Comment by juanmatorres-dev** [comment]
Para hacer  **Borrar la ordenación por flechas** :

- [ ] Quitar la ruta de web.php
- [ ] Comentar el método del controlador de zonas
- [ ] Y comentar las flechas en la vista de zonas

**Comment by juanmatorres-dev** [comment]
Afinando el drag & drop de zonas:

- [ ] Integrar librería JS para convertir el alert a Notifier js

**Comment by juanmatorres-dev** [comment]
Añadir todo lo anterior a la sección de la aplicación (Destacados):

- [ ] Drag & Drop
- [ ] Quitar flechas
- [ ] Añadir Notifier JS con la librería AlertifyJS
