### ISSUE TITLE
Bug en las escenas con hotspot de tipo modelo 3d

### ISSUE THREAD

**Issue by juanmatorres-dev** [avozme/celia-tour#62]
Si hay modelos 3d en una escena y creas nuevos hotspot de tipo salto, en esa escena, tanto si son huérfanos como si no. El panel de administración deja de mostrar todos los hotspot que hay en esa escena, por lo que quedan inaccesibles (ya no se pueden editar).

Para solucionarlo de forma rápida y temporal, puedes eliminar el último hotspot de tipo salto creado (o el que tenga el id correspondiente) desde phpMyAdmin. Pero si no tienes acceso a este, no puedes editar más los hotspot de la escena donde esté el problema desde el panel de administración de la aplicación.

https://user-images.githubusercontent.com/73494826/168818645-f2084737-9e2f-44e7-9198-381aeea7c79b.mp4

**Comment by Rosario095** [comment]
Es cosa de la caché y de alguna cosa de basura que se haya quedado.

https://user-images.githubusercontent.com/94611439/168990303-1692c378-cc10-4146-a056-d8439dad5487.mp4

(perdón la calidad de video, con este usuario no tengo configurado el grabador de videos XD)
